### ISSUE TITLE
Getting error when running LDA

### ISSUE THREAD

**Issue by lpyeh** [USC-CSSL/NTAP#40]
There are some errors with mallet when trying to run LDA on a dataset's text column. A picture of the error is included. 

![Screen Shot 2020-01-28 at 11 55 43 AM](https://user-images.githubusercontent.com/26417696/73410337-bec0aa00-42b6-11ea-848e-63dde2b5caf6.png)

**Comment by Praveensp9** [comment]
Fixed in the latest commit : 47cf662846771f5af34346a1678749755c9c7759.
